services:
  client:
    build: ./client
    ports:
      - "5050:5050"
    depends_on:
      - server
    env_file:
      - ./client/.env
    restart: always

  server:
    build: ./api
    ports:
      - "3000:3000"
    env_file:
      - ./api/.env
    restart: always

